"apiVersion": "crd.k8s.amazonaws.com/v1alpha1"
"kind": "ENIConfig"
"metadata":
  "name": "us-east-2a"
"spec":
  "securityGroups":
  - "sg-032728dd776c8682b"
  "subnet": "subnet-072cc03dae2e27f3c"

---
"apiVersion": "crd.k8s.amazonaws.com/v1alpha1"
"kind": "ENIConfig"
"metadata":
  "name": "us-east-2b"
"spec":
  "securityGroups":
  - "sg-032728dd776c8682b"
  "subnet": "subnet-049755caac87f7024"

---
"apiVersion": "crd.k8s.amazonaws.com/v1alpha1"
"kind": "ENIConfig"
"metadata":
  "name": "us-east-2c"
"spec":
  "securityGroups":
  - "sg-032728dd776c8682b"
  "subnet": "subnet-03def7a6fd320d89d"